### ISSUE TITLE
cannot open spike file recorded from GUI 0.3.3 32bit

### ISSUE THREAD

**Issue by young-gyun** [open-ephys/simpleclust#12] opened 2015-01-12 11:48 UTC
Hi, I tried to openspike file(Tetrode) recorded from GUI by using Simple clust and got this message.

*****
>> simpleclust
open

muafile =

/Volumes/Untitled/Recordings Temp/150108/GUI/2015-01-08_13-05-58/Tetrode1.spikes

Loading spikes file...
Loading failed at block number 1. Found 39355 samples.

Undefined function or variable "channel_gains".

Error in load_open_ephys_data (line 398)
        data(:, :, ch) = double(data(:, :,
        ch)-32768)./(channel_gains(ch)/1000);

Error in sc_loadmuadata (line 12)
        [data, timestamps, info] =
        load_open_ephys_data_sc(muafile);

Error in sc_load_mua_dialog (line 1)
[features,mua]=sc_loadmuadata(features.muafile,1,s_opt);

Error in simple_clust (line 343)
                    sc_load_mua_dialog;

Error in simpleclust (line 3)
simple_clust 
>> 
********

Any suggestion??

**Comment by jvoigts** [comment] 2015-01-12 16:19
Hi,
this is just caused by the outdated loading module in simpleclust - the code currently only handles the older spike format through the load_open_ephys_data function. To update it, you would simply have to copy the current load_open_ephys_data function from the analysis-tools repository into the simpleclust code, i believe the outputs of that function havent changed a lot since, so the rest of the code will likely only need minor adjustments, maybe even none. Let us know if this causes any issues, i'll be able to take a look at this sometime this week.

**Comment by young-gyun** [comment] 2015-01-13 11:47
it works! Thanks Jakob!

**Comment by jvoigts** [comment] 2015-01-13 16:54
Sweet, should be fixed now in 69632c2c13

**Closed by jvoigts** 2015-01-13 16:54 UTC
